### ISSUE TITLE
Follow-up questions for kerbs don't get removed when changing a previous answer

### ISSUE THREAD

**Issue by wielandb** [OPENER-next/OpenStop#114]
### Problem

How to reproduce:

- Select a `public_transport=platform` with no data about the approach aid
- Select that there is a kerb
- Select that the kerb is raised
- Select that there is an approach aid
- Go back until you are asked how high the kerb is
- Answer that the kerb is flushed
- **You will be asked what kind of approach aid the kerb has despite answering that the kerb is flush**
- Go back until you are asked if there is a kerb at this bus stop
- Answer No
- **You will be asked if the kerb has an approach aid despite answering that there is no kerb**

See attached video for demonstration:

https://user-images.githubusercontent.com/29458682/202434338-b26e96d0-55be-445c-bc60-7624842c87df.mp4

### Which app version do you use?

0.2.1+5

### What operating system do you use?

Android

### What operating system *version* do you use?

10

### Additional information

My idea for what is causing this bug:

When changing your answer, only the _next_ card is removed, but there are situations where changing your answer needs to remove multiple cards down the line.

**Comment by Robbendebiene** [comment]
Fixed in cfd15c48d5e683530a59e5e28b4463fcd26cb01b
