### ISSUE TITLE
Update Question Catalog

### ISSUE THREAD

**Issue by Robbendebiene** [OPENER-next/OpenStop#12]
Populate the attribute data structure.
Integrage new tags according to https://wiki.openstreetmap.org/wiki/DELFI_Attribute_-_Barrierefreiheit_im_%C3%96ffentlichen_Personenverkehr
Depends on #11

**1xxx DELFI attributes**
- [x] Questions
- [x] Description Texts
- [x] Images

**2xxx DELFI attributes**
- [x] Questions
- [x] Description Texts
- [x] Images

**Comment by 7h30n3** [comment]
Missing images were added in #93. Finding new and better fitting images and replacing old ones will be an ongoing task.
