### ISSUE TITLE
[Idea] Escalator travel time: Make a button that starts/stops a timer automatically making the value go up

### ISSUE THREAD

**Issue by wielandb** [OPENER-next/OpenStop#130]
### Idea

Solving the question about the escalator travel time is relatively time-consuming, as one has to either use another app with a stopwatch to measure the travel time, or one has to consiously count the number of seconds in one's head. 
I think this put needles cognitive strain on the user and that there is a better solution that I think is easy to implement. 

### Implementation

In the UI for the seconds selection, make a start/stop timer button. When this button is pressed, a timer starts which makes the counter in the UI tick higher every second the same way if a user would increment the UI by one second.   
When the button is pressed again, make the timer stop. So that way, the user can click the button once to start the timer when they get on the escalator, then again when they leave the escalator, and directly upload a reasonably accurate travel time.

**Comment by Robbendebiene** [comment]
I really like the idea!

This could be directly incorporated into the duration input widget.

**Comment by wielandb** [comment]
_[clicks tongue]_ Nice!
