### ISSUE TITLE
[Idea] Limit the size of the red circles?

### ISSUE THREAD

**Issue by wielandb** [OPENER-next/OpenStop#131]
### Idea

Sometimes, the density of stop areas is so high or other factors align wrongly that really **massive** red circles can occur, spanning multiple city blocks at once. This leads to questions getting asked for objects **waaaay outside** the vicinity of any public transport station, like in this example at Halle (Saale) Marketplace:

![photo1672763461](https://user-images.githubusercontent.com/29458682/210399938-cefb00e5-0b68-4f89-ba80-cb3251c69477.jpeg)

### Implementation

So my idea would be: Maybe there could be a maximum size a red circle is allowed to have before two seperate smaller ones generate?

**Comment by Robbendebiene** [comment]
I don't think this is a feasible solution to the problem. The maximum size should at least be as large as something like Berlin main station, which is roughly the size of the circle in your screenshot.

Most of the problems can probably be circumvented by:
- not merging circles of different stop areas
- not asking questions to obviously unrelated objects (like door questions for flats)

While the latter is currently being worked on, the former has some challenges.
Currently the merging algorithm only looks which platforms are close to each other and doesn't make any additional name checks. The main challenges here are that the platform names may differ even though they belong to the same stop area, the stop area relation may be missing, stop area circles may overlap which should be treated with care.

**Comment by wielandb** [comment]
I think, since the red circles are gone, we can close this issue, right?

**Comment by 7h30n3** [comment]
Just for reference, here is a screenshot of the same place:
<img src="https://github.com/OPENER-next/OpenStop/assets/18004390/ac7fd376-5b01-447e-a4e9-44e3155161ac" width="300">

This issue or rather feature request was solved with #172.
