### ISSUE TITLE
Create Ability to add new OSM Elements

### ISSUE THREAD

**Issue by Robbendebiene** [OPENER-next/OpenStop#14]
For accessible routing it is important to know where e.g. people with wheel chairs can cross the street. Thus objects like curb lowerings should be mapped.

Discuss if they should be mapped as ways or POIs (similar to a door).
Explore possible techniques such as drawing on the map or tracking via GPS.

Reference App: https://vespucci.io/ and [OSM Contributor](https://play.google.com/store/apps/details?id=io.mapsquare.osmcontributor&hl=de&gl=US)

**Comment by 7h30n3** [comment]
See: https://www.delfi.de/media/delfi_handbuch_barrierefreie_reiseketten_1._auflage_mai_2018.pdf Page: 49

**Comment by Robbendebiene** [comment]
We decided to not implement this.

Overall it's not a trivial task, especially when it comes to adding elements to relations and reusing/snapping nodes. Also ways can usually better be mapped via satellite imagery.
While simple points of interest could still be valuable we rather focus on OSM notes creation, since the strength of the app is to provide on site information. OSM notes allow contributing information regardless of the type and number of elements.
