### ISSUE TITLE
Questions are asked again after finishing

### ISSUE THREAD

**Issue by Itchiii** [OPENER-next/OpenStop#152]
### Problem

I answered some questions on a point (it was a bus_stop) and clickend on finish. After that the changes were successfully uploaded, but the bus_stop bubble did not disappear and the same questions were asked again. After I also answered these, a change was uploaded to the open changeset but without changes (see image below), the bubble remained.

After I restart the app, the bubble was not longer shown. 

### Which app version do you use?

0.4.0+10

### What operating system do you use?

Android

### What operating system *version* do you use?

8.1.0

### Additional information

![grafik](https://user-images.githubusercontent.com/15103402/226119427-7c5e2d13-cd3e-4e13-9c11-fe68e959ca7a.png)

**Comment by Itchiii** [comment]
Maybe you need the node id: `3249249082`

**Comment by Robbendebiene** [comment]
Thanks for the report.
I tried to reproduce this without any luck so far. After uploading roughly 30 elements none of them failed. If you can remember anything special/different regarding other elements where it worked please let me know.

Also regarding your screenshot, I guess it is supposed to show that no changes occurred? But how can you even detect changes in the same changeset? As far as I know this is not possible.

**Comment by Robbendebiene** [comment]
Thanks for the report.
I tried to reproduce this without any luck so far. After uploading roughly 30 elements none of them failed. If you can remember anything special/different regarding other elements where it worked please let me know.

~~Also regarding your screenshot, I guess it is supposed to show that no changes occurred? But how can you even detect changes in the same changeset? As far as I know this is not possible.~~ The `changes_count="x"` reflects this.
