### ISSUE TITLE
Sometimes, selecting a question will make map grey and UI disappear

### ISSUE THREAD

**Issue by wielandb** [OPENER-next/OpenStop#156]
### Problem

Occasionally, when selecting a quest, the whole map will be replaced with a grey canvas and the control UI (menu, zoom) will vanish. The question UI will remain. 

It is not really reproducable, does not happen consistently on one (type of) object or under some other consistent situation. 

### Which app version do you use?

0.4.0+10

### What operating system do you use?

Android

### What operating system *version* do you use?

10

### Additional information

https://user-images.githubusercontent.com/29458682/231490812-ab51cbf7-c07c-49aa-a703-a79007ea8a57.mp4

**Comment by Robbendebiene** [comment]
This bug should be fixed in the [0.5.0](https://github.com/OPENER-next/OpenStop/releases/tag/v0.5.0) release.
Otherwise please reopen.
