### ISSUE TITLE
Drop shadow of "kerb" icon goes beyond its designated boundary

### ISSUE THREAD

**Issue by 7h30n3** [OPENER-next/OpenStop#173]
### Problem

As it can be seen in the attached images the drop shadow is on top of the marker's white border.

This is a minor issue, which could be fixed by using a different icon or implementing scalable icons, so every icon (and its drop shadow) can be sized to fit inside the borders of the marker.

### Which app version do you use?

v0.4.3

### What operating system do you use?

iOS

### What operating system *version* do you use?

16.4

### Additional information

![Simulator Screenshot - iPhone 14 Pro Max - 2023-05-31 at 13 15 07](https://github.com/OPENER-next/OpenStop/assets/18004390/fb6d267b-77b7-48d7-818a-ee8756998a4c)

**Comment by Robbendebiene** [comment]
I tend to either:
- clip the shadow (or for better performance overlay it with the white marker border)
- adjust the temaki icon font generation

**Comment by Robbendebiene** [comment]
Sort of fixed in 9426881d9eafc9ebfb3c4279b4872f343ac165b0 via clipping.
