### ISSUE TITLE
URI schema `openstop.app` can't be recognized when login via browser in customized OS

### ISSUE THREAD

**Issue by LaoshuBaby** [OPENER-next/OpenStop#212]
### Problem

After I obtain oauth in the browser, I cannot jump back to OpenStop. Is there an in-app login method that does not rely on browser jumps?
As far as I know, for many non-AOSP China mobile phones, calls to URI schemas that are not on the whitelist will not be allowed.

<img src="https://github.com/OPENER-next/OpenStop/assets/42690037/271a6e2b-d2d1-43d0-955b-22b9e20fa8df" width=250px />  <img src="https://github.com/OPENER-next/OpenStop/assets/42690037/4a65aca2-633d-48c1-87ad-ffa4e7be5619" width=250px /> 

(I take screenshot in both `中文(简体)` and `English` locale)

### Which app version do you use?

0.5.0

### What operating system do you use?

Android

### What operating system *version* do you use?

MIUI 12.5.1 (Android 10)

**Comment by 7h30n3** [comment]
Thanks for bringing up the issue. Do you experience the issue with other OSM apps offering OAuth2, too?

**Comment by LaoshuBaby** [comment]
> Thanks for bringing up the issue. Do you experience the issue with other OSM apps offering OAuth2, too?

When I use OSMAnd, I usually use my account and password to log in. I have only used OAuth2 in JOSM, but not on my mobile phone.

It seems that OpenStop only supports this login method?

**Comment by 7h30n3** [comment]
I'm trying to debug that problem. So can you tell me what browser you are using? Is that the native one that comes with MIUI?

**Comment by LaoshuBaby** [comment]
> To narrow down the problem. Can you install Every Door (https://github.com/Zverik/every_door) another Flutter-based OSM editor and check if OAuth works?

In fact, I have used Every Door a few times, but I always used the password to log in.
I just tested it, and as expected, error

![图片](https://github.com/OPENER-next/OpenStop/assets/42690037/8f2ef107-7ef7-4836-a501-ebe528e3ab31)

Subsequently, EveryDoor prompted this error

![图片](https://github.com/OPENER-next/OpenStop/assets/42690037/2cc54f46-bc14-496f-838b-a3b8cb2a1186)

I'm using [Via](https://viayoo.com), which automatically calls the OS's browser kernel, and I changed the default browser to Fennec (the F-Droid version of Firefox ) and then I was able to log in successfully!

It seems that it is indeed related to the browser. There is a problem with the browser kernel of the system. I then used the Fennec browser to successfully log in to OpenStop.

![图片](https://github.com/OPENER-next/OpenStop/assets/42690037/ed5ba591-9b29-4b03-bf5d-321b630ee144)

Thank you for your suggestion. I always mistakenly thought this was an operating system compatibility issue.

**Comment by axelkar** [comment]
Could you use verified app links? I'm using Cromite and getting this error due to [this patch](https://github.com/uazo/cromite/blob/master/build/patches/Disallow-Android-App-Scheme-as-referrer.patch)

**Comment by 7h30n3** [comment]
@axelkar Thanks for bringing this up. We implemented verfied app links for the next version of OpenStop. However this won't fix you problem. 
To fix it (even in the current version) you have to go to your Cromite Settings > Privacy and security > Allow custom tab intents and enable this setting.
