### ISSUE TITLE
Use some translation tool

### ISSUE THREAD

**Issue by matheusgomesms** [OPENER-next/OpenStop#221]
### Idea

Hey guys,

Congrats on making #148 possible! Thanks for that!

Given this is solved, is there any chance to use some tool for translation, such as Weblate, Transifex etc?

It's good to know that it is possible to translate the ARB files, but it's not easy as using any of these services, which are free for FOSS.

**Comment by Robbendebiene** [comment]
Hi thanks for opening this issue.

Integrating a translation tool is definitely the next step 🙂👍
