### ISSUE TITLE
Translation license

### ISSUE THREAD

**Issue by comradekingu** [OPENER-next/OpenStop#234]
### Problem

The newly added translation components state -only explicitly,
which removed from alternatively "or-later" means there is less compatibility and
having to negotiate with each contributor to get it back if need be.

### Which app version do you use?

N/A

### What operating system do you use?

Android

### Additional information

Can be changed in, respectively
https://hosted.weblate.org/settings/openstop/#components
https://hosted.weblate.org/settings/openstop/advanced-question-catalog/
https://hosted.weblate.org/settings/openstop/app/
https://hosted.weblate.org/settings/openstop/fastlane/
https://hosted.weblate.org/settings/openstop/question-catalog/
https://hosted.weblate.org/settings/openstop/glossary/

**Comment by 7h30n3** [comment]
Thank you. I changed the licenses.
