### ISSUE TITLE
Avoid `crossing=zebra` for pedestrian crossings

### ISSUE THREAD

**Issue by Woazboat** [OPENER-next/OpenStop#241]
### Idea

Hi, it seems like you are using [crossing=zebra](https://wiki.openstreetmap.org/wiki/Tag:crossing%3Dzebra) to tag pedestrian crossings with zebra markings. 
https://github.com/OPENER-next/OpenStop/blob/45672a0a3ed018bbd55cacdc5340be2041aab408/assets/question_catalog/definition.json#L2701-L2707

This tag was unfortunately introduced without going through the proposal/community approval process and has since been deprecated by the editor that introduced it. The tag itself suffer from some issues in that it clashes with the rest of the established crossing tagging scheme and has unclear semantics about the presence or absence of traffic signals. 

The (recent but already very widely used) [crossing:markings=*](https://wiki.openstreetmap.org/wiki/Key:crossing:markings) tag can be used to specify the presence and type of markings instead without any coupling to the presence of traffic signals. Complicated and error prone instructions like the one for this quest that are required as a result of mixing signals and markings will also no longer be needed.
https://github.com/OPENER-next/OpenStop/blob/45672a0a3ed018bbd55cacdc5340be2041aab408/assets/question_catalog/locales/en.arb#L429

For reference, StreetComplete also only uses(/used) `crossing=unmarked`, `crossing=marked` (=`crossing=uncontrolled`) and `crossing=traffic_signals`.
https://github.com/streetcomplete/StreetComplete/blob/6a294cc9952073cbfec6075387fb3dff24f1ca06/app/src/main/java/de/westnordost/streetcomplete/quests/crossing_type/CrossingType.kt

(StreetComplete recently moved to exclusively use `crossing:markings=*` + `crossing:signals` without `crossing=*` https://github.com/streetcomplete/StreetComplete/pull/5471)

### Implementation

Either:
- Remove special case answer option for zebra crossings, only set `crossing=unmarked`/`crossing=marked`/`crossing=traffic_signals`. Add quest for type of crossing markings and set `crossing:markings=*`.
- Keep quest as it is. Set `crossing=marked` + `crossing:markings=zebra` instead of `crossing=zebra`.
- Do what StreetComplete does now and only ask for `crossing:signals` and `crossing:markings` and don't set `crossing=*`at all.

**Comment by 7h30n3** [comment]
@Woazboat Thanks for bringing up th feature request.
I have created a PR: https://github.com/OPENER-next/OpenStop/pull/242 adressing this request.
We have decided to use the third approach, which means doing it like StreetComplete. Maybe you can check if it's like you proposed.

One question remains. In the OSM wiki it is stated that `crossing=*` is required for `crossing:markings=*`. (See https://wiki.openstreetmap.org/wiki/Key:crossing:markings) What's you opinion on that?

**Comment by 7h30n3** [comment]
Fixed in #242
