### ISSUE TITLE
Summary text for curbs with approach aids does not match

### ISSUE THREAD

**Issue by divergentdave** [OPENER-next/OpenStop#246]
### Problem

When submitting information about the curb at a bus stop, if I answer no to "Does the stop have a special curb with an approach aid for buses?", the confirmation fragment says "Access ramp: No". Judging by the English translation file, these two are directly related to the same property, but referring to an "access ramp" for the first time on the confirmation page is confusing. I think this should be changed to say "Approach aid".

### Which app version do you use?

0.6.0+16

### What operating system do you use?

Android

### What operating system *version* do you use?

14

**Comment by 7h30n3** [comment]
Thank you for pointing this out. I don't know how this could slip through.
Fixed with 2a10aec
