### ISSUE TITLE
App flagged by Google Play Protect

### ISSUE THREAD

**Issue by ben20471** [OPENER-next/OpenStop#254]
### Problem

When I install the latest update from F-Droid, I get a pop-up from Gogle Play Protect telling me that the app may collect data that could be used to track my activities, and when I click "see more", it says that it may be dangerous for my device (may not be accurate as I'm translating it from my display language). It happens both when upgrading and when re-installing.

### Which app version do you use?

0.7.0

### What operating system do you use?

Android

### What operating system *version* do you use?

12 (Go edition)

**Comment by ben20471** [comment]
Just checked, it doesn't happens with the Google Play version, so the problem might directly be F-Droid

**Comment by 7h30n3** [comment]
Thanks for pointing out this "issue". We can recreated the behavoir. The good thing is one can install the app from F-Droid anyhow by clicking on "More details".
We first thought it might be an update in the google play services which falsely detect OpenStop as dangerous, but if you install OpenStop 0.6.1 from F-Droid the warning doesn't appear.
We will investigate a possible solution.

**Comment by licaon-kter** [comment]
> latest update from F-Droid, I get a pop-up from Gogle Play Protect telling me that 

Does EU need to raise the pressure on Google? :shrug:
