### ISSUE TITLE
Missing Option for no markings at a crossing

### ISSUE THREAD

**Issue by wurzel-3** [OPENER-next/OpenStop#261]
### Problem

When asked for the type of marks at a crossing there is no option to select, that there are no crossings. The crossing in this case has a pedestrian island in the middle of the road.

### Which app version do you use?

0.7.0+18

### What operating system do you use?

Android

### What operating system *version* do you use?

13

### Additional information

![Screenshot_20240417-151440_OpenStop](https://github.com/OPENER-next/OpenStop/assets/32613909/ab30a48c-1cc8-479c-b17b-7555683e2396)

**Comment by 7h30n3** [comment]
As you can so in the conditions on the corresponding question: https://github.com/OPENER-next/OpenStop/blob/f5e89defe1199ba6746c859c2b5a45f9b1ce57d0/assets/question_catalog/definition.json#L3183-L3221

We only ask this question, when particular conditions are met.
So I guess in you case, someone tagged wrong tags on the element.

**Comment by Robbendebiene** [comment]
@wurzel-3 Can you please send us the link to the element this question is/was asked for?

**Comment by Robbendebiene** [comment]
Thanks for the element. This is indeed a bug. We should no ask the question there as it is tagged as
```
crossing=unmarked
crossing:markings=no
```

**Comment by Robbendebiene** [comment]
**Update:** Turns out this is actually not a bug.
OpenStop does not ask the question for the crossing node, it asks it for the crossing way https://www.openstreetmap.org/way/1023973084 which is tagged with:

```
crossing=marked
crossing:markings=yes
```

Therefore OpenStop asks for a more detailed value of `crossing:markings=yes`

**Comment by wurzel-3** [comment]
Ok, than that is definitely a wrong tagging which i'm going to correct. 
As it is not a bug, i will close this issue.
