### ISSUE TITLE
OpenStop web in English

### ISSUE THREAD

**Issue by idotj** [OPENER-next/OpenStop#268]
### Idea

`/web` folder in the repo doesn't match with the official website _openstop.app_
Source code of the website can be useful to be available for the community to help for translations.

**Comment by 7h30n3** [comment]
Hi, you are right the content of the `/web` folder does not represent the official website openstop.app.
The source code for the website can be found in this repo: https://github.com/OPENER-next/OpenStop-website. Unfortunately there was no preliminary work for the website to be translated in different languages.

**Comment by idotj** [comment]
Thanks @7h30n3 
I will then move this issue to the right repo:

https://github.com/OPENER-next/OpenStop-website/issues/1
