### ISSUE TITLE
Speech output in reality is not necessarily combined with passenger information display.

### ISSUE THREAD

**Issue by dreirund** [OPENER-next/OpenStop#276]
### Problem

Speech output question is only asked when "passenger information display" question is answered with yes.

But there are cases where there is only speech output, no live display (only paper timetable ans speech output).

### Which app version do you use?

0.8.1+20

### What operating system do you use?

Android

### What operating system *version* do you use?

11

**Comment by wielandb** [comment]
Could you provide a picture of something like that?

Well, the question is meant to explicitly ask if the passenger information display has speech output, but there is a question that asks for `announcement=`, maybe it could be used?

**Comment by dreirund** [comment]
> Could you provide a picture of something like that?

I do not remember where this was. On some of my travels.

**Comment by Robbendebiene** [comment]
It may also be possible to tag `speech_output` directly directly on the platform in this case, but we first need to better understand the scenario. Did you encounter this on a bus or train platform? Where was the button located? Where was the speaker located?

**Comment by dreirund** [comment]
> It may also be possible to tag `speech_output` directly directly on
> the platform in this case, but we first need to better understand the
> scenario. Did you encounter this on a bus or train platform? Where
> was the button located? Where was the speaker located?

It was on a bus platform. The button was on the post which did hold
the stop sign.

Other information was only the writte (not-realtim) timetable.

**Comment by dreirund** [comment]
> Okay. In this case we could think about tagging something like this:
> ```
> public_transport=platform
> pole=yes
> pole:speech_output=yes
> ```
> 
> See: https://wiki.openstreetmap.org/wiki/Key%3Apole

OK!

**Comment by dreirund** [comment]
I re-thinked it:

> > Okay. In this case we could think about tagging something like this:
> > ```
> > public_transport=platform
> > pole=yes
> > pole:speech_output=yes
> > ```
> > 
> > See: https://wiki.openstreetmap.org/wiki/Key%3Apole  
> 
> OK!

I think that the passenger information is nothing that is related to
the other stuff at the stop, so having it as a property of the pole is
I think not the right way to go.

There is the
[`departures_board`](https://wiki.openstreetmap.org/wiki/Key:departures_board) key which actually has a few more options than just `yes` and `no`. Maybe using this and adding a value `speech_output` to it could be an idea?

(e.g. `departures_board=delay;realtime;speech_output` if those three
properties are present?)

Regards!
