### ISSUE TITLE
Allow translation of PT-BR

### ISSUE THREAD

**Issue by matheusgomesms** [OPENER-next/OpenStop#287]
### Problem

Hallo!

I've been using OpenStop for a while, in Brazilian Portuguese (PT-BR), but while the app is in PT-BR, the questions are rather in PT.

I checked Weblate, and saw that the Question Catalog and Fastlane components were not enabled. I enabled them 3 days ago, but the strings to be translated didn't appear yet (0 strings). Is there any problem with Weblate or something has to be enabled here?

Thanks!

### Which app version do you use?

Latest

### What operating system do you use?

iOS

**Comment by 7h30n3** [comment]
Hi @matheusgomesms Thanks for bringing up the issue.

I just checked if PT-BR can be translated and as you can see in the screenshots it seems totally possible to me.
![Screenshot 2024-08-28 at 15 20 01](https://github.com/user-attachments/assets/64cfa558-e2af-4969-aab7-e0971fb62a71)
![Screenshot 2024-08-28 at 15 20 39](https://github.com/user-attachments/assets/f05e6617-65a9-4556-b565-fc399d10716e)


If it shows the same for you, we can close the issue.

**Comment by matheusgomesms** [comment]
Hi René,

Thanks for the reminder. Yes, for some reason it took around 10 days since I opened this issue to Weblate create the strings in PT-BR. Don't know the reason, but yeah, now it's available for translation.

Thanks a lot!
