### ISSUE TITLE
Cycle & Foot Paths are marked as Footpaths

### ISSUE THREAD

**Issue by gy-mate** [OPENER-next/OpenStop#298]
### Problem

Cycle & Foot Paths are marked just as Footpaths when selected. This confused me a bit when the question about the cycle line popped up.

### Which app version do you use?

`0.8.2+21`

### What operating system do you use?

iOS

### What operating system *version* do you use?

`18.1`

### Additional information

See the example below:

![IMG_4966](https://github.com/user-attachments/assets/5db11aa0-6d4b-43ba-87d9-698923d367e6)
https://www.openstreetmap.org/way/1327358338

**Comment by Robbendebiene** [comment]
Thanks for the report.

What do you think of splitting the footway into three categories:
- footway: https://github.com/rapideditor/temaki/blob/main/icons/pedestrian.svg
- cycleway: https://fonts.google.com/icons?selected=Material+Symbols+Outlined:directions_bike:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=cycle&icon.size=24&icon.color=%235f6368
- shared/combined: https://github.com/rapideditor/temaki/blob/main/icons/pedestrian_and_cyclist.svg

Main question is how do we name the combination of foot- and cycleway?

**Comment by gy-mate** [comment]
> What do you think of splitting the footway into three categories:
> 
> * footway: https://github.com/rapideditor/temaki/blob/main/icons/pedestrian.svg
> * cycleway: https://fonts.google.com/icons?selected=Material+Symbols+Outlined:directions_bike:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=cycle&icon.size=24&icon.color=%235f6368
> * shared/combined: https://github.com/rapideditor/temaki/blob/main/icons/pedestrian_and_cyclist.svg

@Robbendebiene That's a good idea!

> Main question is how do we name the combination of foot- and cycleway?

I suggest _Cycle & Foot Path_, as iD calls them.
