### ISSUE TITLE
Show Map Markers for Ways and Areas

### ISSUE THREAD

**Issue by 7h30n3** [OPENER-next/OpenStop#40]
- [x] Implement Center Point Calculation
- [x] Highlight selected Way/ Area
- [x] The retrieved data for relations can be incomplete. It misses ways and nodes that are necessary to build the multipolygon because they lie outside of the queried bounding box.
- [x] Revisit center point calculation for Polygons

**Comment by Itchiii** [comment]
> Highlight selected Way/ Area

Would be great, because the default layer doesn't render a platform yet. And through that, it could be confusing.

**Comment by 7h30n3** [comment]
In order to answer questions about the width of a sidewalk we should somehow visualize the direction, especially when tags like `sidewalk:right:width `or `sidewalk:left:width` are attached to it.

**Comment by Robbendebiene** [comment]
Done.
The way direction is tracked in a dedicated issue:  #135
