### ISSUE TITLE
Location determination just works with Google?

### ISSUE THREAD

**Issue by Itchiii** [OPENER-next/OpenStop#73]
### The problem

The app has the location permission and my location sharing is on but it doesn't work inside the app. A screen appeared that I should active the location services by Google (see Screenshot). If I clicked on "Nein Danke/No Thanks" nothing happened. And I won't to activate these Google services. I have no problems with this in other apps like OsmAnd.

### Which app version do you use?

0.1.0+1

### What operating system do you use?

Android

### What operating system *version* do you use?

8.1.0

### Additional information

![Screenshot_2022-05-06_12-21-22](https://user-images.githubusercontent.com/15103402/167115577-787c3748-951b-4c3a-b640-cf67a1cb16c4.png)

**Comment by 7h30n3** [comment]
Unfortunately this issue lays upstream in the geolocator package.
I created an corresponding issue: https://github.com/Baseflow/flutter-geolocator/issues/1114

**Comment by Robbendebiene** [comment]
I haven't tested this, but you should now be able to circumvent this by installing the [F-Droid build](https://f-droid.org/en/packages/de.tu_chemnitz.etit.sse.openstop/) of the app which doesn't use any Google Services.

**Comment by 7h30n3** [comment]
I have testded it. Using the F-Droid version fixes this issue. 
The F-Droid version is recommended if you don't have or don't want to use Google Services for a more precise location.
If somehow the issue still persists on your device, we can re-open the issue.
