### ISSUE TITLE
Indicate that the upload is in progress

### ISSUE THREAD

**Issue by Robbendebiene** [OPENER-next/OpenStop#79]
Currently after clicking the "upload button" nothing will happen until the upload is completed. While this works quite well when having a good connection, uploading data with a slow connection may take longer. Thus we should show some kind of indeterminate progress indicator.

Ideas:
- Animate the arrow of the upload button icon, or the entire icon
- Animate the progress bar (behind the upload button)

Example:
<img src="https://ds6br8f5qp1u2.cloudfront.net/blog/wp-content/uploads/2017/05/0sM8xtgfVHFRfHNwj.gif?x82505">

**Comment by 7h30n3** [comment]
PR #85 introduced a snackbar message, if upload was successfull or erroneous.

**Comment by Robbendebiene** [comment]
PR #263 introduced an icon animation **for the marker** that is currently being uploaded. The upload button is not animated as we immediately close the sheet so the user can continue without having to wait.

Also the "upload success" snackbar message was removed.
