### ISSUE TITLE
F-Droid Link in the Readme.md is 404

### ISSUE THREAD

**Issue by 1Maxnet1** [OPENER-next/OpenStop#88]
Hi,

when I follow the link to check the App on F-Droid I only get a 404 page. Is the App available on F-Droid and could you provide a link or fix the existing one?

Regards

Max

**Comment by 7h30n3** [comment]
Unfortunately the F-Droid release is on hold right now due ambiguities about used allegedly proprietary packages.

https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10991

The readme was created before hoping the F-Droid release is a non-issue and not updated since.

**Comment by 7h30n3** [comment]
Because we couldn't fix the issue with the proproprietary packages the MR for F-Droid was finally closed. Until we came up with a better new solution we will remove the F-Droid link from the readme file.

**Comment by 1Maxnet1** [comment]
A short time workaround would be to offer stable releases over a third party repository (e.g. https://android.izzysoft.de/repo/info offers to include apps in his repository). This would enable f-droid users to add the repository and use the app, until the issue is resolved.
